## Importing Dependecies

In [1]:
import pandas as pd

<hr>

## Definging Helper Functions

In [13]:
# function for getting all the unique values in a column in a df
def col_unique_val(df,colname):
    uniq_vals = []
    for index,row in df.iterrows():
        for col,value in row.items():
            if col == colname and value not in uniq_vals:
                uniq_vals.append(value)
    return uniq_vals

# function for getting all the values in a row in a df
def row_values(df,row_index):
    values = df.loc[row_index].values
    return values
    
# function to check for rows with NaN values and which row index and columns they are in
def null_rows(df):
    null_rows = df.isnull().any(axis=1)  # identify rows with null values
    null_indexes = null_rows[null_rows].index  # get index of null rows
    if len(null_indexes) == 0:
        print("No rows with null values found.")
    else:
        print(f"Rows with null values (total {len(null_indexes)}):")
        for i in null_indexes:
            print(f"Row {i}: {list(df.columns[df.loc[i].isnull()])}")
            
# function for exporting a df as a csv
def exportCSV(df):
    headerOBJ = df.columns
    header = []
    for item in headerOBJ:
        header.append(item)
        
    filename = input('Please Enter The Name of CSV ->\n')

    # define the desired formatting options
    format_options = {'sep': ';',  # use semicolon as delimiter
                      'index': False,  # don't include index column
                      'float_format': '%.2f',  # format float values to 2 decimal places
                      'header': header,  # rename headers
                      'encoding': 'utf-8'}  # specify encoding type

    # export the dataframe to CSV using the formatting options
    df.to_csv(filename,**format_options)

In [127]:
# NOT USING THIS BLOCK!!!
#First lets find the maximum column for all the rows
'''
with open("YT_datasets_raw/first_crawl/2008_crawl/080727/3.txt", 'r') as temp_f:
    # get No of columns in each line
    col_count = [ len(l.split(",")) for l in temp_f.readlines() ]

### Generate column names  (names will be 0, 1, 2, ..., maximum columns - 1)
column_names = [i for i in range(max(col_count))] 
'''

In [5]:
# Example list of lists
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]

# Get the maximum length of the inner lists
max_len = max(len(lst) for lst in my_list)

# Create a list of column names
cols = [f"col_{i+1}" for i in range(max_len)]

# Create an empty DataFrame with the specified columns
df = pd.DataFrame(columns=cols)

# Populate the DataFrame with the values from the input list
for i, lst in enumerate(my_list):
    # If the inner list is shorter than the maximum length,
    # pad it with None values to match the length of the DataFrame
    if len(lst) < max_len:
        lst = lst + [None] * (max_len - len(lst))
    # Add the values from the inner list to a new row in the DataFrame
    df.loc[i] = lst

# Display the resulting DataFrame
print(df)

   col_1  col_2  col_3  col_4
0    1.0    2.0    3.0    NaN
1    4.0    5.0    6.0    NaN
2    7.0    8.0    9.0   10.0

In [5]:
# read the tab-separated text file into a Pandas DataFrame

# set the variable for the ALL the file paths
# for April 2007 -->>
fpath1 = "first_crawl\\April2007\\0403"
fpath2 = "first_crawl\\April2007\\0410"
fpath3 = "first_crawl\\April2007\\0413"
fpath4 = "first_crawl\\April2007\\0418"
fpath5 = "first_crawl\\April2007\\0420"
fpath6 = "first_crawl\\April2007\\0422"
fpath7 = "first_crawl\\April2007\\0424"
fpath8 = "first_crawl\\April2007\\0426"
fpath9 = "first_crawl\\April2007\\0428"
fpath10 = "first_crawl\\April2007\\0430"
# for April 2008 -->>
fpath11 = "first_crawl\\April2008\\080402"
fpath12 = "first_crawl\\April2008\\080404"
fpath13 = "first_crawl\\April2008\\080406"
fpath14 = "first_crawl\\April2008\\080408"
fpath15 = "first_crawl\\April2008\\080412"
fpath16 = "first_crawl\\April2008\\080414"
fpath17 = "first_crawl\\April2008\\080416"
fpath18 = "first_crawl\\April2008\\080418"
fpath19 = "first_crawl\\April2008\\080422"
fpath20 = "first_crawl\\April2008\\080424"
fpath21 = "first_crawl\\April2008\\080426"
fpath22 = "first_crawl\\April2008\\080428"
fpath23 = "first_crawl\\April2008\\080430"
# for updated 2007 -->>
fpath24 = "updated_crawl\\2007_crawl_u\\0402u"
fpath25 = "updated_crawl\\2007_crawl_u\\0409u"
fpath26 = "updated_crawl\\2007_crawl_u\\0416u"
# for updated 2008 -->>
fpath27 = "updated_crawl\\2008_crawl_u\\080416u"
fpath28 = "updated_crawl\\2008_crawl_u\\080423u"
fpath29 = "updated_crawl\\2008_crawl_u\\080430u"



def folderTOdf(folder_path):
    file_path = folder_path + "/{0}.txt"

    #set the column names
    col_name = ['video ID', 'uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1','related ID2',
                'related ID3','related ID4','related ID5','related ID6','related ID7','related ID8','related ID9','related ID10','related ID11','related ID12',
                'related ID13','related ID14','related ID15','related ID16','related ID17','related ID18','related ID19','related ID20','related ID21',
                'related ID22']

    # loop over the file paths and read each file into a DataFrame

    # for loop for creating df from one entire folder
    df_list = []
    for i in range(4):
        # create the file path string with the variable i
        path = file_path.format(i)
        # read the file into a DataFrame
        df = pd.read_csv(path, delimiter='\t',header = None,names=col_name,low_memory=False)
        df = df.drop(columns=['related ID21','related ID22'])
        df_list.append(df)
    return df_list  #will contain 4 dfs - one for each level of crawl.

In [72]:
# making df
df = folderTOdf(fpath1)
df[1].head(21)

,video ID,uploader,age,category,length,views,rate,ratings,comments,related ID1,...,related ID11,related ID12,related ID13,related ID14,related ID15,related ID16,related ID17,related ID18,related ID19,related ID20
0,-L6tFCeR_ZQ,daniela2c,776.0,Music,249.0,1467.0,4.73,11.0,14.0,W91sqAs-_-g,...,gL3EjCPu-Q4,8Eaj9OZ--K0,_oPYs-LNYGo,f2uBfi4miC8,gJ0I92_1Vt8,n58uchRpgO0,q_U2xh1cHBk,wJaMJ9wgHNc,jDVPJ_7dS3k,w8dpP4uQglk
1,SgHk5JDCdx0,djdavidh,776.0,Music,249.0,1038.0,3.20,5.0,6.0,W91sqAs-_-g,...,_oPYs-LNYGo,GzqvzhpLfIg,f2uBfi4miC8,8Eaj9OZ--K0,mj7mYbHEasI,gJ0I92_1Vt8,n58uchRpgO0,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk
2,4U5dmIVBzq8,GhostIntimidation,776.0,Music,249.0,5290.0,4.22,27.0,15.0,W91sqAs-_-g,...,_oPYs-LNYGo,f2uBfi4miC8,GzqvzhpLfIg,mj7mYbHEasI,8Eaj9OZ--K0,gJ0I92_1Vt8,n58uchRpgO0,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk
3,MwzSxbqyzcE,AceHardon,776.0,Music,139.0,2072.0,1.65,37.0,17.0,W91sqAs-_-g,...,_oPYs-LNYGo,GzqvzhpLfIg,f2uBfi4miC8,8Eaj9OZ--K0,mj7mYbHEasI,gJ0I92_1Vt8,n58uchRpgO0,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk
4,UFMx8fkpLNg,sstitanic,629.0,Music,35.0,1336.0,0.00,0.0,0.0,lLtz7kd0OXo,...,9nSapARYcCw,aTvs1hIxk0o,rMZT1D2iDD0,b1J8C2T9MHI,aVY2mDxAZl0,PaD4gBYhIgc,E0GNQoi4uZY,wFQiKCWefVY,5DB5eJvD-K0,naYpkhjRVfY
5,XJaHmGD8UEk,SergioMartorelli,776.0,Music,249.0,260.0,5.00,1.0,1.0,W91sqAs-_-g,...,gL3EjCPu-Q4,8Eaj9OZ--K0,_oPYs-LNYGo,gJ0I92_1Vt8,n58uchRpgO0,mj7mYbHEasI,jDVPJ_7dS3k,TKsBgV78NSI,KizKliQvF_M,w8dpP4uQglk
6,_oPYs-LNYGo,TB163,776.0,Entertainment,166.0,591.0,3.00,5.0,7.0,W91sqAs-_-g,...,Jl2AaYYgIXo,gL3EjCPu-Q4,8Eaj9OZ--K0,f2uBfi4miC8,gJ0I92_1Vt8,mj7mYbHEasI,n58uchRpgO0,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk
7,GzqvzhpLfIg,supratime,777.0,Comedy,191.0,231.0,1.00,1.0,1.0,W91sqAs-_-g,...,gL3EjCPu-Q4,8Eaj9OZ--K0,_oPYs-LNYGo,gJ0I92_1Vt8,n58uchRpgO0,mj7mYbHEasI,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk,TNnBZva8tMk
8,f2uBfi4miC8,Tammerajean,776.0,Entertainment,249.0,1035.0,4.33,9.0,4.0,XJaHmGD8UEk,...,w8dpP4uQglk,jDVPJ_7dS3k,oGhl8ySfKHY,xO3pzL9klmE,KVq0haf7yUU,f5UuP4HXCbE,-L6tFCeR_ZQ,4U5dmIVBzq8,_oPYs-LNYGo,GzqvzhpLfIg
9,8Eaj9OZ--K0,bknight61,777.0,Music,250.0,1248.0,5.00,5.0,4.0,_-zMMZ4aFmc,...,MCg3xRBCB2w,aE9GHf6PlDg,vBWIzHCNT-8,YWqqNZQhuX0,cKCJWGRrvtg,yeituQskqU8,ONWq2GhT2kI,gv9bmut2V6Q,yD53lfWMrMU,IM4rl97Ow60
10,mj7mYbHEasI,gannondork,774.0,Entertainment,141.0,3777.0,1.73,11.0,16.0,W91sqAs-_-g,...,Jl2AaYYgIXo,gL3EjCPu-Q4,8Eaj9OZ--K0,_oPYs-LNYGo,f2uBfi4miC8,gJ0I92_1Vt8,n58uchRpgO0,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk
11,gJ0I92_1Vt8,bariskkm,777.0,Entertainment,14.0,288.0,1.00,1.0,15.0,W91sqAs-_-g,...,Jl2AaYYgIXo,gL3EjCPu-Q4,8Eaj9OZ--K0,_oPYs-LNYGo,f2uBfi4miC8,n58uchRpgO0,q_U2xh1cHBk,wJaMJ9wgHNc,jDVPJ_7dS3k,w8dpP4uQglk
12,n58uchRpgO0,Cogmaid,777.0,Music,34.0,297.0,0.00,0.0,0.0,W91sqAs-_-g,...,abGQ_ehWm2Y,_oPYs-LNYGo,GzqvzhpLfIg,f2uBfi4miC8,mj7mYbHEasI,8Eaj9OZ--K0,gJ0I92_1Vt8,jDVPJ_7dS3k,KizKliQvF_M,w8dpP4uQglk
13,jDVPJ_7dS3k,InfoAlerts,741.0,Entertainment,110.0,1118.0,0.00,0.0,0.0,oGhl8ySfKHY,...,zMmIRU3JirQ,ktbd8yPBxkU,0DQ4ga8ZUlk,Rrcfs2BuIhk,dEWTknrmUGk,rCGQMDO9dLU,gBE-nt2Pm28,vTlG-qh4BFw,ebxLjR9bUqo,T8RmmBa_3U4
14,KizKliQvF_M,osopolae,773.0,Music,243.0,38383.0,3.53,70.0,60.0,eaTVI5NjAUE,...,uInP-RAArvI,ybaXlX5q2OE,BxWKIXIyL1g,sARqCa5Cqu4,up-RX_YN7yA,fjcpciuIPp4,i5oKmO6TAxo,z5lPfzlUW7Q,CvgINs2bVHo,oV0ThTK0Ut4
15,4acBKXjveJI,jwbtown,500.0,Autos & Vehicles,153.0,356.0,1.00,1.0,0.0,Zk22r_GJV-Q,...,B-bGOyfPtdE,5TE1iHKS0Zc,6zdXhC4yySs,SvYDYrKTfVg,mfV5F-AAkCM,BqSlunU0kts,kJe4JvlYCAE,nj7aeHVvBO4,Nb2DtnQep-8,h3ac69ux45k
16,Zk22r_GJV-Q,jwbtown,500.0,Autos & Vehicles,420.0,251.0,0.00,0.0,0.0,4acBKXjveJI,...,iMR9scfrsx0,B-bGOyfPtdE,5TE1iHKS0Zc,6zdXhC4yySs,SvYDYrKTfVg,mfV5F-AAkCM,BqSlunU0kts,kJe4JvlYCAE,nj7aeHVvBO4,Nb2DtnQep-8
17,resxQ9PgiqY,SOMUCHFORFREEMEDIA,770.0,News & Politics,159.0,854.0,4.95,19.0,21.0,klBlNKNbv_4,...,WtF0l-yuL6E,zTGvPrrkVAA,XPi7afE2gS4,fPYEs033Kmk,On2wmy0Wb9o,8Hj9K5cvejg,m1n5IkW-Yp4,1OO_WrdvvIk,m3a5OHs6Yzk,YIgOn1kRw5s
18,ttk-52Zm9Gk,afuelsaver,774.0,Autos & Vehicles,104.0,63.0,0.00,0.0,0.0,4acBKXjveJI,...,A2-e3Fgah5A,mHnV2L-RuDo,tJBQUM52dhw,6NbqZy-8FGg,jHV4RZsl-bI,c1lwEBlfvDE,_z_aMmcfhvQ,ehOy22LGtz0,7k59WCFsPME,Msv3Dgb5KXE
19,0V5_b9eGufU,freefuelsaver,773.0,Autos & Vehicles,104.0,3887.0,0.00,0.0,0.0,oqcaJ4NrUKA,...,Xo4spN5h808,-LRhNlm6aXA,ODhTmU-n_ew,4tFDLj89kHc,SffxZcrrSIk,J0KJffC9UTo,CQr3MnK1RF4,oxpFaLBuMQw,SO5HIOn7Y-w,HNo4m1OJrM8
20,1YJpUWyOgjY,CARMATECARMATE,667.0,Autos & Vehicles,222.0,1452.0,0.00,0.0,0.0,uPmMZph9wSc,...,J3HK8snqn-o,T_P-bwmCcAM,9jyCfRHumHU,LTUtOAh--M8,qTaGc1uKUCM,VxheEdKhDgE,hPrpVyttGWM,dXCwcjHphKI,jRAGcr5zWFU,H-eO1F3-Wjc

In [76]:
folderList = [fpath1]
folder_df_list = []   # will contain the number of df_lists equal to the number of
# file paths provided.
for path in folderList:
    folder_df_list.append(folderTOdf(path))
#folder_df_list.clear()
#print(folder_df_list)

## Cleaning the DFs

- Checking for NaN values
- Removing the rows with NaN values in `category` column only

In [77]:
for path in folder_df_list:
    for df in path:
        null_rows(df)
        break
    break

Rows with null values (total 30):
Row 5: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 6: ['related ID20']
Row 7: ['related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 20: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 23: ['related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 51: ['related ID19', 'related ID20']
Row 64: ['related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 67: ['related ID19', 'related ID20']
Row 75: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 81: ['related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 82: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 90: ['related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 100: ['related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 104: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 108: ['related ID19', 'related ID20']
Row 109: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 118: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 120: ['related ID20']
Row 145: ['related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 161: ['related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 169: ['related ID20']
Row 177: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 188: ['related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 199: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 217: ['related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 239: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 247: ['related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 296: ['related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 311: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 324: ['related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']

In [79]:
col_name = ['video ID', 'uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1','related ID2',
            'related ID3','related ID4','related ID5','related ID6','related ID7','related ID8','related ID9','related ID10','related ID11','related ID12',
            'related ID13','related ID14','related ID15','related ID16','related ID17','related ID18','related ID19','related ID20','related ID21',
            'related ID22']


for path in folder_df_list:
    for df in path:
            df = df[df['category'].notna()]
           
    
#for item in cate_null:   
    #for item in df:
        #df = df.drop(item)

print(df.head(25))

       video ID              uploader    age        category  length   views  \
0   FqHjVyJxOlQ      cherrysuedemusic  700.0           Music   374.0   193.0
1   TA12H7AYXhg            Wisegeorge  761.0           Music   217.0    69.0
2   43He52iMidE            Wisegeorge  762.0   Entertainment   139.0   143.0
3   WQ9JPCzhPe4             sadeyes35  762.0           Music    60.0    59.0
4   eCfXAO2cGN8  carlygoodwinofficial  664.0           Music    19.0   301.0
5   d7XhbFpPbW0   hillbillyRockstar11  614.0           Music   278.0   169.0
6   7M9VKmXsAj4          tantalus6138  548.0  People & Blogs    20.0   155.0
7   eRJNgSIberk         georgeanton77  581.0           Music   227.0   141.0
8   dwcvLtY-rwo     coffeysouthernman  758.0           Music   267.0   243.0
9   3D-SgA_NJwk       barefootnatives  743.0           Music   211.0   278.0
10  qXqp0k7unlw            engnsokmen  761.0           Music   222.0   579.0
11  clrbTyXBWEQ             Eflatun78  746.0           Music   150.0   911.0
12  cSoKa7AU9Sw               ebilcan  643.0           Music   229.0  2599.0
13  nF4Hc7vnsEM               34bjk21  746.0           Music   154.0   309.0
14  OzqQsWbYRfU           phoenix0256  772.0           Music    86.0    46.0
15  vJWOIFNFQik                ltimur  648.0           Music   152.0  3001.0
16  XzCtEXBYlDc      fatalerrorturkey  775.0           Music   183.0   125.0
17  hLKDjMrHvow             Brokennnn  744.0           Music   295.0  3360.0
18  nhZg9sXEwAM             Brokennnn  721.0           Music   196.0   818.0
19  TmgEKsyQmB0             bobohakan  707.0           Music   193.0  1330.0
20  fx8SItJGISk                 iso17  770.0           Music    73.0   123.0
21  nMNbrBauFVQ             serbululu  659.0           Music   222.0  2536.0
22  44iiteNE2Xo                 erd87  727.0           Music   253.0  1251.0
23  jSRp6fQpw18            sercanince  749.0           Music   243.0   669.0
24  usoZPaM6gK0           kapkara3480  721.0           Music   100.0   805.0

    rate  ratings  comments  related ID1  ... related ID11 related ID12  \
0   5.00      2.0       0.0  NqyQHu2syWM  ...  Qkx7Qs46pio  Ufxe5pMVyik
1   5.00      1.0       0.0  RPmL-_haRac  ...  2RKBMX2gthQ  8IxT6nUVxF0
2   5.00      1.0       2.0  bVukbHmONMI  ...  ZRUElUbj68I  UGyxdyJo52I
3   0.00      0.0       0.0  x20j6KojaGA  ...  U2DBcbZc3ck  lpvINN4C58Y
4   0.00      0.0       0.0  YbwgoGSxXTw  ...  -5hU9n8uILI  4D4I1bTEstw
5   0.00      0.0       0.0  lE5l4HD6wlE  ...  owhq-iffZBw  aPfiNXRG2cM
6   0.00      0.0       0.0  WjzMFWMQMh8  ...  6_7XsvZTggE  wWuPe1ZFLm8
7   0.00      0.0       0.0  talMlrhpwx8  ...  YSzN8l5ql94  USonCd_kBYQ
8   5.00      1.0       2.0  _84q2QjqLZE  ...  axJh50lQc5k  s3HbGh7lgM4
9   5.00      3.0       2.0  jH7qNqKlPE4  ...  7t4ZHPr4-v4  vFITCElCvXM
10  5.00      2.0       2.0  KzFjhH_g1uk  ...  Nb5u_NR87qI  pUZue4P_t5M
11  4.90     10.0      11.0  WZnr22f1Fgg  ...  hK50T8u49ro  FbUBlHkIIpw
12  3.50      8.0       4.0  i6gcikdw8wY  ...  3w2EgPeL2zw  jKPmryyXgIY
13  5.00      5.0       0.0  fUGqf5Hl580  ...  3jdEhDxgJHs  GLeTpfx5sG8
14  0.00      0.0       0.0  ifZYaY9ioLE  ...  m4jcvX8rL6I  holmt_mojZU
15  4.85     13.0       9.0  cpgPIq-pTfI  ...  BL1b-svcZa0  mw-kNurDrGw
16  4.00      4.0       0.0  MS3aqV-GW3Y  ...          NaN          NaN
17  4.00      3.0       3.0  k6u3AiMVahQ  ...  pn5gcNtn48U  CbzM0B2sZls
18  4.83      6.0       6.0  -MdapXaEOnU  ...  Yyf8vtMB45U  J45_OqAgVH0
19  5.00      3.0       6.0  cSoKa7AU9Sw  ...  3jdEhDxgJHs  GLeTpfx5sG8
20  5.00      2.0       1.0  zssiOT0lGqs  ...  eUhLXokkjXU  pO3QMcmgRis
21  4.67      6.0       2.0  eFvKCfuV310  ...  44iiteNE2Xo  TmgEKsyQmB0
22  2.80      5.0      24.0  nMNbrBauFVQ  ...  usoZPaM6gK0  GLeTpfx5sG8
23  5.00     11.0       7.0  hOP1lwo4i7Y  ...  q3KGIlo2Ry8  -pGJldTOhB4
24  0.00      0.0       1.0  29KVz0xIZg8  ...  yujKNG6aAFI  4ZGWVtQt1Ig

   related ID13 related ID14 related ID15 related ID16 related ID17  \
0   IIO2qpSsUTA  cBDMthZ0c80  d3WoGz7VRoI  xK8VzuF9zqE  n82CUEQCz6I
1   AOFpQd7aJ9U  s5btZWbViPA  tJWk7v0oVfk  tfDzU7GrH50  uuGUaCd5w8U
2   1md6IrLK-JQ  YewaSLASBi0  Fuh7gCT_zH4  k07HYxt0FKc          NaN
3   olOYynQ-_Hw  WDhkO22OZeo  HTWtFDcSHDg  H2Ncxw1xfck  QM-mfEMssy8
4   0B15M3j2qNg  SWYE0gvAffA  Et1_TtStxyY  xrGChT8GW84  zApM-0qaAdM
5   l3kEjch6vbw  MDTYr06iGDI  dWWmjNx-OMY  5sfPh9OLUmM  NTH90h4zLwc
6   V-DJ8CKafn4  oySRHEW4jks  LYYcLU1EK6o  _-qd3fGfTo8  Mq70VXSXp3I
7   azjD_tSxQw8  43VZGGvYDzQ  BWmYRj1MGms  7vTU6e5Sces  Jk3SXscIEVY
8   8vP5PNr6mX4  nwB6amVSPC8  rrvSq1RGe8c  R-TtYIGWOVs  NGLvhFRs3s0
9   uv2hs0RJbIY  OH0UTH9U3QQ  wMypZDSm5A8  OEezS2hgRO4  utaLmUQg9ks
10  qyHUMwVGDCg  qXekqBvNM-4  PXa8CZGfIfE  oYfacqq3aK8  h5uXf2nX3pQ
11  1i8eRlZpsJ0  XyUo6LnXH2Q  JspuSFLL-K4  m_o44BZ8LpU  nPfFtY46rNg
12  3WIb7ojq-ug  -0AUBeHspPk  rBQ20_IA708  XCb1MyRT20k  b4_ogbNE_6k
13  ow8dakULw4E  caLOEkBWC0I  eFvKCfuV310  vJWOIFNFQik  yeituQskqU8
14  6P2Trlra1X0  wvHkWJHPnZ8  vc3oZ-C5Ypk  fPZC6meTc4w  JuVwRnFksCA
15  ZQWCnHJrWLA  T0ImfqZ7s18  9ricQQC6Rvw  yeituQskqU8  8wbX73q2_1A
16          NaN          NaN          NaN          NaN          NaN
17  0qYFHGbD_8g  eu1iHeBdce8  A2qJzTGcTLA  uRDiiv54IJ4  dxYDrDYFr9U
18  RvSkOHxBEiw  Sq6RuSetCLk  TiNzhNx_h2Y  aNguPLc9P0c  kNPZCBydTOE
19  ow8dakULw4E  caLOEkBWC0I  eFvKCfuV310  vJWOIFNFQik  yeituQskqU8
20  zbJjjwHA-nU  qNM7AjPS9yw  HLNlWOIUxfE  hK50T8u49ro  FbUBlHkIIpw
21  tF48QjzegCs  fx8SItJGISk  -khwa0tctdo  cSoKa7AU9Sw  jSRp6fQpw18
22  2h9jjoH3xsQ  nA-KhegCcz8  cVDdey_M5JU  ow8dakULw4E  vJWOIFNFQik
23  ihrq3gSmVTo  RTGcN_g1U7M  SAxTsCu8YFA  uNV0LUbi2X0  sPBiWMZ8vdk
24  0plTyBlgG9c  i51bX9JHq1U  CrPhYOgF2mU  WfS_1_csN6Q  zkw1GfzXVWY

   related ID18 related ID19 related ID20
0   pMDn6V7ZLhE  UbBSDE-Dywo  k51P2DrLXDw
1   WIB-YZ3m4wA  CN_tHhHSLP4  T56vLzS5i5w
2           NaN          NaN          NaN
3   0EwVJD0k2r0  5_1RqyNdzbE  kBz9-_r1rC8
4   8gUF9G4N-tE  SjNyU42Q3Qg  MuI7mcUWdC0
5   w178taGowTg  aG2kdP3eLVM  VCRfurZEVDs
6   g_KYv1EtDzs  B2rNwGPA42A  rGiZemTiIkw
7   dyt6yuCWh7Y  xp_ohY_3N7Q  _XG4q0m_xy8
8   5NaQPxnSRWI  5j8ia9qWzkU  1psdQc7UwJ4
9   tmblKB6-YBc  Vj_W3k8xF9o  s6P6_kG9ov0
10  h8fE7MFC1qE  6emMY_p07m4  6PonKWaYhpE
11  tHj3MP9Cplw  FcqMKublK3A  OCbwbswavys
12  VEULKk2YoU0  uIMhLznGQCY  WxDI3MJeKYM
13  cVDdey_M5JU  rBQ20_IA708  2h9jjoH3xsQ
14  qz0eAwpwhGs  -B7Ru0ANmko  V5RliKxFARM
15  KPaDE2Lsnd8  YgIJFnK5si4  CC2jIbRj3EE
16          NaN          NaN          NaN
17  vRzeau13bBs  dr_RmVL3xzU  E-lpwUlTQfk
18  u0Vw2y_xYdE  5jeszwiDUS0  VyFT7Qg5J7o
19  cVDdey_M5JU  2h9jjoH3xsQ  noOgLHR13qw
20  1i8eRlZpsJ0  XyUo6LnXH2Q  JspuSFLL-K4
21  caLOEkBWC0I  usoZPaM6gK0  GLeTpfx5sG8
22  noOgLHR13qw  rBQ20_IA708  nF4Hc7vnsEM
23  RJQaYig58Ks  VTFG3Fh2Zec  nTW2gXBqkhg
24  rghuy-DpbNY  kVgI8LEcumM  Cqma--22mCY

[25 rows x 29 columns]

In [60]:
for path in folder_df_list:
    for df in path:
        null_rows(df)
        break
    break

Rows with null values (total 30):
Row 5: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 6: ['related ID20']
Row 7: ['related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 20: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 23: ['related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 51: ['related ID19', 'related ID20']
Row 64: ['related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 67: ['related ID19', 'related ID20']
Row 75: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 81: ['related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 82: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 90: ['related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 100: ['related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 104: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 108: ['related ID19', 'related ID20']
Row 109: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 118: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 120: ['related ID20']
Row 145: ['related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 161: ['related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 169: ['related ID20']
Row 177: ['related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 188: ['related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 199: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 217: ['related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 239: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 247: ['related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 296: ['related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 311: ['uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1', 'related ID2', 'related ID3', 'related ID4', 'related ID5', 'related ID6', 'related ID7', 'related ID8', 'related ID9', 'related ID10', 'related ID11', 'related ID12', 'related ID13', 'related ID14', 'related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']
Row 324: ['related ID15', 'related ID16', 'related ID17', 'related ID18', 'related ID19', 'related ID20']

## Exporting the df as CSV

In [38]:
exportCSV(df)

Please Enter The Name of CSV ->
 test.csv

In [60]:
#extract the columns which actually contain the data for the first entry.
colval = df.columns
for item in colval:
    print(item)

ly0dBk7yqYU smosh 1zzzzzComedy
364
415091
4.77
10505
12464
MV95TjaXkX8
vVhSDhDOHh0
jfACnjzXc3o
gkVTdVzoL6A
uWAxLCkpPW4
zzAFEtwIoAw
3iguSOqYAVg
sA2kG2p9INU
MZX0VXLq54w
PawWL2Hml4I
7qM-_ez_5kY
0Ci_GcBeJpU
Wpgeu_dy8zw
U0_CuZHtq_Y
thWS6L1WMiE
Jwzoi05VDts
xqdjb-XkzG4
JYLectcOOi0
PCHG2tIt2RY
v1qkmQPJIcU

In [61]:
#Rename the columns
col_name = ['video ID', 'uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1','related ID2',
            'related ID3','related ID4','related ID5','related ID6','related ID7','related ID8','related ID9','related ID10','related ID11','related ID12',
            'related ID13','related ID14','related ID15','related ID16','related ID17',]
df.columns=col_name
df.head()

,,,video ID,uploader,age,category,length,views,rate,ratings,comments,related ID1,...,related ID8,related ID9,related ID10,related ID11,related ID12,related ID13,related ID14,related ID15,related ID16,related ID17
AknyR-kRvLc,JamesNintendoNerd,1256.0,Comedy,639.0,133590.0,4.89,4159.0,2600.0,rmeMGbJvu9E,aeGBf5lnhhY,vYVGslS0itE,JILwrJWKTAU,...,TpNY3BY8jQk,7M6s1e_O4tI,clXt2ueJAaU,m4WPt9AZY9c,uQdqMfw9iuU,-8g_OTJ6OE8,5rm-FVsBVcI,NCeVW_oevvM,FWRs6X3y310,Lhj1IoVgjn8
49hC9TpP_rY,JohnMcCaindotcom,1257.0,News & Politics,33.0,267795.0,2.38,1017.0,1700.0,mm9IUfPZsX8,Au0eBx05Zxc,4yU2-LTFLf0,Z0cNqtUtufo,...,Fw2KxSWs0hA,gO35AwPtn9o,_1brJ8tuN8w,2hEzGKQLmU4,f2bGDgfHZvQ,gMTSIWXZ8ts,mTSuHweJXxc,f-mdHN24iS0,kD3LTtYXl2A,HqlyqG6tNh0
n7Oxb5kaBBE,charlieissocoollike,1257.0,People & Blogs,175.0,46592.0,4.88,1333.0,1606.0,9_u-sWwyWI8,T6jPQ6Ftesg,rEycXsyVu_U,SQ_HHV8vdAE,...,7sfuJjA1sTs,Q9KQVZVGZrk,CT5tGAu-rPs,tzwKmU3Y59M,g06Ruui5gs4,HPsH0vmTHQw,jk1DSWkCa-U,IaUxVKfuzOc,xYJDSYMT_E4,CipqpMFk2Jk
sb3JbXuTkE8,makemebad35,1258.0,Entertainment,136.0,10367.0,4.86,1381.0,1580.0,v924OISPPpY,Bhi-Dv1ou6s,ETg3OZaTjWA,vHlLnJGOux8,...,UosS4rbn5Ks,yavvUNS4-bI,EA4AIERt83A,gb0eVsg50xM,_UzFrPdP3lc,saSNRofAFVE,s8wt91rs550,V732zA4yZsk,5kC4F86fejc,y5gVGcxrbIw
OJ3XQK_Wvmc,vlogbrothers,1258.0,Howto & Style,227.0,206.0,4.97,312.0,1534.0,ywUYymEQALo,3GeRpsbYYz4,64TAvw6RsGc,HpSZCmGDpH4,...,qM_2ogAxEms,tHpihMsJoYk,_CvykZL334I,7fXGKvu234M,G5skzLS9RGU,cQKjTcVDul0,4K9EEAm8WI0,4R75-_6eQ5I,gMK2x03-tWg,SAnBXO-hpKo

In [63]:
df = df.reset_index()
df = df.drop(columns=['index'])
df.head()

,level_0,level_1,level_2,video ID,uploader,age,category,length,views,rate,...,related ID8,related ID9,related ID10,related ID11,related ID12,related ID13,related ID14,related ID15,related ID16,related ID17
0,AknyR-kRvLc,JamesNintendoNerd,1256.0,Comedy,639.0,133590.0,4.89,4159.0,2600.0,rmeMGbJvu9E,...,TpNY3BY8jQk,7M6s1e_O4tI,clXt2ueJAaU,m4WPt9AZY9c,uQdqMfw9iuU,-8g_OTJ6OE8,5rm-FVsBVcI,NCeVW_oevvM,FWRs6X3y310,Lhj1IoVgjn8
1,49hC9TpP_rY,JohnMcCaindotcom,1257.0,News & Politics,33.0,267795.0,2.38,1017.0,1700.0,mm9IUfPZsX8,...,Fw2KxSWs0hA,gO35AwPtn9o,_1brJ8tuN8w,2hEzGKQLmU4,f2bGDgfHZvQ,gMTSIWXZ8ts,mTSuHweJXxc,f-mdHN24iS0,kD3LTtYXl2A,HqlyqG6tNh0
2,n7Oxb5kaBBE,charlieissocoollike,1257.0,People & Blogs,175.0,46592.0,4.88,1333.0,1606.0,9_u-sWwyWI8,...,7sfuJjA1sTs,Q9KQVZVGZrk,CT5tGAu-rPs,tzwKmU3Y59M,g06Ruui5gs4,HPsH0vmTHQw,jk1DSWkCa-U,IaUxVKfuzOc,xYJDSYMT_E4,CipqpMFk2Jk
3,sb3JbXuTkE8,makemebad35,1258.0,Entertainment,136.0,10367.0,4.86,1381.0,1580.0,v924OISPPpY,...,UosS4rbn5Ks,yavvUNS4-bI,EA4AIERt83A,gb0eVsg50xM,_UzFrPdP3lc,saSNRofAFVE,s8wt91rs550,V732zA4yZsk,5kC4F86fejc,y5gVGcxrbIw
4,OJ3XQK_Wvmc,vlogbrothers,1258.0,Howto & Style,227.0,206.0,4.97,312.0,1534.0,ywUYymEQALo,...,qM_2ogAxEms,tHpihMsJoYk,_CvykZL334I,7fXGKvu234M,G5skzLS9RGU,cQKjTcVDul0,4K9EEAm8WI0,4R75-_6eQ5I,gMK2x03-tWg,SAnBXO-hpKo

In [65]:
#Rename the columns
col_name = ['video ID', 'uploader', 'age', 'category', 'length', 'views', 'rate', 'ratings', 'comments', 'related ID1','related ID2',
            'related ID3','related ID4','related ID5','related ID6','related ID7','related ID8','related ID9','related ID10','related ID11','related ID12',
            'related ID13','related ID14','related ID15','related ID16','related ID17','related ID18','related ID19','related ID20']
df.columns=col_name
df

,video ID,uploader,age,category,length,views,rate,ratings,comments,related ID1,...,related ID11,related ID12,related ID13,related ID14,related ID15,related ID16,related ID17,related ID18,related ID19,related ID20
0,AknyR-kRvLc,JamesNintendoNerd,1256.0,Comedy,639.0,133590.0,4.89,4159.0,2600.0,rmeMGbJvu9E,...,TpNY3BY8jQk,7M6s1e_O4tI,clXt2ueJAaU,m4WPt9AZY9c,uQdqMfw9iuU,-8g_OTJ6OE8,5rm-FVsBVcI,NCeVW_oevvM,FWRs6X3y310,Lhj1IoVgjn8
1,49hC9TpP_rY,JohnMcCaindotcom,1257.0,News & Politics,33.0,267795.0,2.38,1017.0,1700.0,mm9IUfPZsX8,...,Fw2KxSWs0hA,gO35AwPtn9o,_1brJ8tuN8w,2hEzGKQLmU4,f2bGDgfHZvQ,gMTSIWXZ8ts,mTSuHweJXxc,f-mdHN24iS0,kD3LTtYXl2A,HqlyqG6tNh0
2,n7Oxb5kaBBE,charlieissocoollike,1257.0,People & Blogs,175.0,46592.0,4.88,1333.0,1606.0,9_u-sWwyWI8,...,7sfuJjA1sTs,Q9KQVZVGZrk,CT5tGAu-rPs,tzwKmU3Y59M,g06Ruui5gs4,HPsH0vmTHQw,jk1DSWkCa-U,IaUxVKfuzOc,xYJDSYMT_E4,CipqpMFk2Jk
3,sb3JbXuTkE8,makemebad35,1258.0,Entertainment,136.0,10367.0,4.86,1381.0,1580.0,v924OISPPpY,...,UosS4rbn5Ks,yavvUNS4-bI,EA4AIERt83A,gb0eVsg50xM,_UzFrPdP3lc,saSNRofAFVE,s8wt91rs550,V732zA4yZsk,5kC4F86fejc,y5gVGcxrbIw
4,OJ3XQK_Wvmc,vlogbrothers,1258.0,Howto & Style,227.0,206.0,4.97,312.0,1534.0,ywUYymEQALo,...,qM_2ogAxEms,tHpihMsJoYk,_CvykZL334I,7fXGKvu234M,G5skzLS9RGU,cQKjTcVDul0,4K9EEAm8WI0,4R75-_6eQ5I,gMK2x03-tWg,SAnBXO-hpKo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,aSXnUdS7Z1E,PACKimPOTT,1258.0,Music,571.0,20.0,0.00,0.0,0.0,LV0iiZSPENg,...,oF0FZcogdGo,-rTZHzwumtw,qb38LHfntgA,yYi-Ec1osCg,PCIpRpaveoE,PQaZulcMaMc,7UF5F5QmMZE,77sC1TPb3bE,6wuM106EyVg,Tkc7ywt0DlQ
177,wyw-VNitc0g,mayureshbakshi,1258.0,Entertainment,200.0,2.0,0.00,0.0,0.0,vYkKZ04rX3Q,...,XiKGZFX-hcA,5uWctFLkQOQ,JsEyuB25S5g,xl4V4UBM9zQ,0hz6A_aP-nc,cd2DxsxQEuU,vHWlB6tCC6c,OTYPI5bBy5g,nw3leOmp6Jw,okvSba7vdI0
178,-oVQwlDB9Rg,mishekent,1258.0,Comedy,61.0,0.0,0.00,0.0,0.0,7vowfuhjXCg,...,2tJjNVVwRCY,XM3ki-FF-p0,La209OKkUgI,EBSrN-EZYMY,qhmahD_EbHY,kfgrnyv3q1g,3aG5G38GzhU,HtkOLRuAXDY,aAFoNy2-nF8,q1OG0iNKTBo
179,o0logXPc4w0,VideoGame420,1258.0,Gaming,173.0,0.0,0.00,0.0,0.0,aOXmtioEiI4,...,au2ZygipYA0,Kl8EAQnsWag,Cw36yw6BzwI,IUcWRxH9j30,Nwrm3qO_0MU,7cdgWaxucqo,1zod6r_xnqs,1CCTtwH73cA,qpf-kDznwzY,37geO8Aihjs
180,FjOqWqumw9w,nic3824,1258.0,Film & Animation,0.0,0.0,0.00,0.0,0.0,gMsafWZWnBQ,...,qDGrRcMtSk8,BG-vRl1-ufQ,2YkiIGpdRuw,U8RMLsDd4f4,z6FmDwRX-lY,mKCzWWfFHJQ,gu4WlFYpr7g,nuv26EVXUJI,b0p9RMMSNyE,84jZajXB2C8

### Information regarding to the Video-Network dataframe

`VIDEO-ID` : contains a hashcode id for the videos on youtube.An 11-digit string, which is unique <br>
`UPLOADER` : contains the name of the uploader as a string value.<br>
`AGE` : an integer number of days between the date when the video was uploaded and Feb.15, 2007 (YouTube's establishment)<br>
`CATEGORY` : a string of the video category chosen by the uploader<br>
`LENGTH` : an integer number of the video length in seconds _(my deduction)_ <br>
`VIEWS` : an integer number of the views<br>
`RATE` : a float number of the video rate.<br>
`RATING` : an integer number of the ratings<br>
`COMMENTS` : an integer number of the comments.<br>
`RELATED-IDx` : up to 20 strings of the related video IDs. _the related videos are stacked horizontally_<br>

## Reading the User-Info files

In [196]:
#Rename the columns
Ucol_name = ['user ID', 'uploads', 'watches', 'friends']

userfile_path = 'YT_datasets_raw/user-info/0528/user.txt'
df_user = pd.read_csv(userfile_path,delimiter='\t',header = None)
df_user.columns=Ucol_name
df_user

                      user ID  uploads  watches  friends
0                000000000000      2.0   4058.0      0.0
1        00000000000000000Jew     17.0      8.0      0.0
2        0000000000000000bomb     23.0     21.0      0.0
3        0000000000000000hate      4.0     28.0      0.0
4        0000000000000000iran     19.0     13.0      0.0
...                       ...      ...      ...      ...
1062319           zzzzzxzzzzz      5.0     70.0      0.0
1062320            zzzzzz1000      4.0      1.0      0.0
1062321           zzzzzzapata      5.0     60.0      0.0
1062322            zzzzzzzaq1     11.0      2.0      0.0
1062323            zzzzzzzzap     11.0    309.0     13.0

[1062324 rows x 4 columns]

### Information regarding to the User-Info dataframe

`USER-ID` : contains a hashcode id for the users on youtube _1062324 rows_ <br>
`UPLOADS` : contains the number of videos uploaded by the user. _Datatype==Float_<br>
`WATCHES` : contains the times the videos uploaded by the user have been watched.<br>
`FRIENDS` : contains the count of number of added friends of the user on youtube. _Datatype==Float_<br>

In [190]:
#Rename the columns
Uidcol_name = ['user ID']

useridfile_path = 'YT_datasets_raw/user-info/0528/userid.txt'
df_userid = pd.read_csv(useridfile_path,delimiter='\t',header = None)
df_userid.columns=Uidcol_name
df_userid.head()

                user ID
0          000000000000
1  00000000000000000Jew
2  0000000000000000bomb
3  0000000000000000hate
4  0000000000000000iran

In [195]:
#Rename the columns
vidmetacol_name = ['video ID', 'length', 'size', 'bitrate']

useridfile_path = 'YT_datasets_raw/video-size_bitrate/080908sizerate/sizerate.txt'
df_vidmeta = pd.read_csv(useridfile_path,delimiter='\t',header = None)
df_vidmeta.columns=vidmetacol_name
df_vidmeta

           video ID  length        size  bitrate
0       hu28avESP68     281  11163226.0  318.323
1       PmI76gyuWcM     342         NaN      NaN
2       2jldx-Mu5oY      98   3574440.0  294.696
3       N5A1YNfp_Ks      64   2662492.0  334.326
4       4XoZjB3lTfo     241   9760074.0  325.149
...             ...     ...         ...      ...
153705  OzdeFCTFAd4     214   8843285.0  329.231
153706  UhvGdmaL6X0     511  12601143.0  196.038
153707  mgNpMDa5Qbs     465         NaN      NaN
153708  3cMJg4aUAt4      53   2196161.0  324.921
153709  yYsuGx6e0GM      79   2844588.0    284.6

[153710 rows x 4 columns]

### Information regarding to the Video-Meta dataframe

`VIDEO-ID` : contains a hashcode id for the videos _153710 rows_<br>
`LENGTH` : contains the length of the video is seconds<br>
`SIZE` : contains the size of the video in integer number of bytes.<br>
`BITRATE` : contains the video bitrate (double number of kbps)<br>

> <span style='color:red'>CAUTION! </span>
    The df contains NaN values which need to be replaced with some other value or drop those rows.

### Reading the updated video metadata files

In [34]:
pathU = 'YT_datasets_raw/updated_crawl/2008_crawl_u/080903u/update.txt'
col_nameU = ['video ID', 'views', 'rate', 'rating','comments']
dfU = pd.read_csv(pathU, delimiter='\t',header = None,names=col_nameU,low_memory=False)
dfU

           video ID      views  rate  rating  comments
0       gFa1YMEJFag   433756.0  4.66  7256.0    6636.0
1       pSJ4hv28zaI        NaN   NaN     NaN       NaN
2       uHVEDq6RVXc  2334687.0  4.62  8796.0    8717.0
3       K7Om0QZy-38   641524.0  3.86  3450.0    3728.0
4       DCAO6bZa31o   249200.0  3.52   430.0    1752.0
...             ...        ...   ...     ...       ...
161080  iQGMn_iiWZo      152.0  0.00     0.0       1.0
161081  UqS-vWQH7es     2812.0  5.00     4.0       4.0
161082  JepyoDy8Lys     2058.0  5.00     2.0       1.0
161083  CxXD2oT7cps      265.0  5.00     2.0       1.0
161084  AFaH6cRll2I     4925.0  4.83     6.0      10.0

[161085 rows x 5 columns]